apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432 # port in the service object
      targetPort: 5432 #port in the pod.

  selector:
    name: postgres-pod
    app: demo-voting-app