apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80 #port in the service object
      targetPort: 80 #port in the pod
      nodePort: 30005
  selector:
    name: voting-app-pod
    app: demo-voting-app